package com.infosys.ultra.auditors.dto;

public enum IndustryType {
	MINING_AND_QUARRYING("MINING AND QUARRYING"), FISHING("FISHING"), AGRICULTURE("AGRICULTURE"), FORESTRY("FORESTRY"),
	HUNTING("HUNTING"), AUTOMOBILE_PRODUCTION("AUTOMOBILE PRODUCTION"), TEXTILE("TEXTILE"),
	CHEMICAL_ENGINEERING("CHEMICAL ENGINEERING"), AEROSPACE("AEROSPACE"), SHIP_BUILDING("SHIP BUILDING"),
	ENERGY_UTILITIES("ENERGY UTILITIES"), RETAIL_SALES("RETAIL SALES"),
	TRANSPORTATION_AND_DISTRIBUTION("TRANSPORTATION AND DISTRIBUTION"), RESTAURANTS("RESTAURANTS"), TOURISM("TOURISM"),
	INSURANCE_AND_BANKING("INSURANCE AND BANKING"), HEALTHCARE_SERVICES("HEALTHCARE SERVICES"),
	LEGAL_SERVICES("LEGAL SERVICES"), RESEARCH_AND_DEVELOPMENT("RESEARCH AND DEVELOPMENT"),
	INFORMATION_TECHNOLOGY("INFORMATION TECHNOLOGY "), EDUCATION("EDUCATION"),
	CONSULTING_SERVICES("CONSULTING SERVICES");

	private String industryType;

	IndustryType(String industryType) {
		// TODO Auto-generated constructor stub
		this.industryType = industryType;
	}
	
	public String getIndustryType() {
		return industryType;
		
	}
	

}
